site_name: Avoiding Fees As Angi Services (formerly Handy) Pro
copyright: Copyright &copy; 2022 Robinson Handy and Technology Services LLC

# repository information
remote_name: origin
remote_branch: website

# Development server details
# dev_addr: 192.168.1.103:8000

# # Appearance
theme:
  name: material
  language: en
  font:
    text: Ubuntu
    code: Ubuntu Mono
  palette:
    - scheme: default
      primary: black
      accent: red
  features:
    - toc.integrate

nav:
  - index.md
  - readthedocumentation.md
  - showupontime.md
  - leaveappopen.md
  - timezonedifferences.md
  - takephotos.md
  - storytimenightstand.md
  